//go:build darwin

package platform

import (
	"fmt"
	"os/exec"
	"sort"
	"strings"
)

// firewallAnchor lives under com.apple/* so the default pf.conf
// evaluates it without us touching /etc/pf.conf.
const firewallAnchor = "com.apple/f2f-mac-fw"

// InstallFirewall loads (or replaces atomically) the f2f pf anchor
// from the OS-agnostic FirewallPolicy. pfctl -f swaps the anchor's
// ruleset in one syscall, so callers may reinvoke this to update
// the allow list without an in-between window of broken filtering.
func InstallFirewall(p FirewallPolicy) error {
	rules := buildPfRules(p)
	cmd := exec.Command("/sbin/pfctl", "-a", firewallAnchor, "-f", "-")
	cmd.Stdin = strings.NewReader(rules)
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Include the ruleset we attempted to load — pfctl's "syntax
		// error" messages reference a line number, useless without
		// the source.
		return fmt.Errorf("pfctl -a %s -f -: %w: %s\nruleset:\n%s", firewallAnchor, err, out, rules)
	}
	return nil
}

// RemoveFirewall flushes the f2f pf anchor. Idempotent — flushing an
// already-empty anchor succeeds silently.
func RemoveFirewall() error {
	out, err := exec.Command("/sbin/pfctl", "-a", firewallAnchor, "-F", "all").CombinedOutput()
	if err != nil {
		return fmt.Errorf("pfctl -a %s -F all: %w: %s", firewallAnchor, err, out)
	}
	return nil
}

// buildPfRules renders the policy as a pf ruleset. pf uses last-
// matching-rule semantics (no `quick` here), so within the to-us
// subset: `block` first, then `pass` rules override per match. ICMP
// to us is always allowed (ping diagnostics). State is kept on every
// pass so return packets fly. Outbound (`out on`) is fully permitted.
func buildPfRules(p FirewallPolicy) string {
	var sb strings.Builder
	sb.WriteString("# generated by f2f; do not edit by hand\n")
	fmt.Fprintf(&sb, "pass out on %s keep state\n", p.Iface)
	fmt.Fprintf(&sb, "block in on %s from any to %s/32\n", p.Iface, p.TunnelIP)
	fmt.Fprintf(&sb, "pass in on %s proto icmp from any to %s/32 keep state\n", p.Iface, p.TunnelIP)

	tcp := append([]int(nil), p.AllowTCP...)
	udp := append([]int(nil), p.AllowUDP...)
	sort.Ints(tcp)
	sort.Ints(udp)
	if len(tcp) > 0 {
		fmt.Fprintf(&sb, "pass in on %s proto tcp from any to %s/32 port { %s } keep state\n",
			p.Iface, p.TunnelIP, joinInts(tcp))
	}
	if len(udp) > 0 {
		fmt.Fprintf(&sb, "pass in on %s proto udp from any to %s/32 port { %s } keep state\n",
			p.Iface, p.TunnelIP, joinInts(udp))
	}
	return sb.String()
}

func joinInts(xs []int) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprint(x)
	}
	return strings.Join(parts, " ")
}
