//go:build linux

package platform

import (
	"fmt"
	"os/exec"
	"sort"
	"strings"
)

// firewallTable is the nftables table where f2f's rules live. Using
// the inet family covers IPv4 and IPv6 in one table.
const firewallTable = "inet f2f"

// InstallFirewall replaces the f2f nftables table atomically. nft
// rolls back on any error inside the script, so partial state is not
// possible.
func InstallFirewall(p FirewallPolicy) error {
	rules := buildNftRules(p)
	cmd := exec.Command("nft", "-f", "-")
	cmd.Stdin = strings.NewReader(rules)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("nft -f -: %w: %s\nruleset:\n%s", err, out, rules)
	}
	return nil
}

// RemoveFirewall deletes the f2f nftables table. Not-found is
// non-fatal.
func RemoveFirewall() error {
	out, err := exec.Command("nft", "delete", "table", "inet", "f2f").CombinedOutput()
	if err != nil {
		// "No such file or directory" / "does not exist" → table
		// already gone, treat as success.
		msg := strings.ToLower(string(out))
		if strings.Contains(msg, "no such") || strings.Contains(msg, "does not exist") {
			return nil
		}
		return fmt.Errorf("nft delete table %s: %w: %s", firewallTable, err, out)
	}
	return nil
}

// buildNftRules renders the policy as an nftables script. The header
// ensures the table exists, then deletes it, then recreates from
// scratch — all in one `nft -f` transaction so the swap is atomic
// (nft either commits the whole script or rolls it all back).
func buildNftRules(p FirewallPolicy) string {
	var sb strings.Builder
	sb.WriteString("# generated by f2f; do not edit by hand\n")
	// Atomic replace: declare-then-delete is a no-op if the table is
	// already present; the empty declare ahead of delete makes the
	// pattern safe on the very first install too.
	sb.WriteString("table inet f2f {}\n")
	sb.WriteString("delete table inet f2f\n")
	sb.WriteString("table inet f2f {\n")
	fmt.Fprintf(&sb, "  chain input {\n")
	fmt.Fprintf(&sb, "    type filter hook input priority 0; policy accept;\n")
	// Pass return traffic for connections we initiated — TCP replies
	// to outbound HTTP, etc. macOS pf does this implicitly via
	// `keep state`; nft needs it as an explicit ct rule.
	fmt.Fprintf(&sb, "    iif \"%s\" ct state established,related accept\n", p.Iface)
	// Only filter packets arriving on our tunnel and destined for us.
	fmt.Fprintf(&sb, "    iif \"%s\" ip daddr %s icmp type echo-request accept\n", p.Iface, p.TunnelIP)

	tcp := append([]int(nil), p.AllowTCP...)
	udp := append([]int(nil), p.AllowUDP...)
	sort.Ints(tcp)
	sort.Ints(udp)
	if len(tcp) > 0 {
		fmt.Fprintf(&sb, "    iif \"%s\" ip daddr %s tcp dport { %s } accept\n",
			p.Iface, p.TunnelIP, joinIntsCSV(tcp))
	}
	if len(udp) > 0 {
		fmt.Fprintf(&sb, "    iif \"%s\" ip daddr %s udp dport { %s } accept\n",
			p.Iface, p.TunnelIP, joinIntsCSV(udp))
	}
	// Default-deny tail for our tunnel_ip; everything else passes per
	// the chain's accept policy.
	fmt.Fprintf(&sb, "    iif \"%s\" ip daddr %s drop\n", p.Iface, p.TunnelIP)
	sb.WriteString("  }\n")
	sb.WriteString("}\n")
	return sb.String()
}

func joinIntsCSV(xs []int) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprint(x)
	}
	return strings.Join(parts, ", ")
}
