# fly.toml app configuration file generated for f2f-camp on 2026-05-17T18:05:00+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'f2f-camp'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'

[[services]]
  protocol = 'udp'
  internal_port = 3478

  [[services.ports]]
    port = 3478

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
